name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Summary
      id: strings
      shell: bash
      run: |
        echo "Operating system=${{matrix.os}}"
        echo "Python Version=${{matrix.python-version}}"

    - name: Check cmake
      shell: bash
      run: cmake --version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Print Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get Coverage
      uses: orgoro/coverage@v3.2
      with:
        coverageFile: coverage.xml
        thresholdAll: 0.8
        thresholdNew: 0.9
        sourceDir: ios_build

    - name: Generate Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        thresholds: '50 80'
