name: "Generate issues from TODOs"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Generate issues"
        uses: alstr/todo-to-issue-action@v5
        with:
          INSERT_ISSUE_URLS: "true"
          CLOSE_ISSUES: "true"
          
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin ${{ github.ref }}
          else
            echo "No changes to commit"
          fi
